TAB_MAPPING =
{
  [9] = {"Cities", "Littleroot Town"}, -- Littleroot Town
  [256] = {"Cities", "Littleroot Town"}, -- Littleroot Town - Brenden's House 1F
  [257] = {"Cities", "Littleroot Town"}, -- Littleroot Town - Brenden's House 2F
  [258] = {"Cities", "Littleroot Town"}, -- Littleroot Town - May's House 1F
  [259] = {"Cities", "Littleroot Town"}, -- Littleroot Town - May's House 2F
  [260] = {"Cities", "Littleroot Town"}, -- Littleroot Town - Professor Birch's Lab
  [10] = {"Cities", "Oldale Town"}, -- Oldale Town
  [512] = {"Cities", "Oldale Town"}, -- Oldale Town - House 1
  [513] = {"Cities", "Oldale Town"}, -- Oldale Town - House 2
  [514] = {"Cities", "Oldale Town"}, -- Oldale Town - Pokemon Center 1F
  [515] = {"Cities", "Oldale Town"}, -- Oldale Town - Pokemon Center 2F
  [516] = {"Cities", "Oldale Town"}, -- Oldale Town - Mart
  [0] = {"Cities", "Petalburg City"}, -- Petalburg City
  [2048] = {"Cities", "Petalburg City"}, -- Petalburg City - Wally's House
  [2049] = {"Cities", "Petalburg Gym"}, -- Petalburg City - Gym
  [2050] = {"Cities", "Petalburg City"}, -- Petalburg City - House 1
  [2051] = {"Cities", "Petalburg City"}, -- Petalburg City - House 2
  [2052] = {"Cities", "Petalburg City"}, -- Petalburg City - Pokemon Center 1F
  [2053] = {"Cities", "Petalburg City"}, -- Petalburg City - Pokemon Center 2F
  [2054] = {"Cities", "Petalburg City"}, -- Petalburg City - Mart
  [3] = {"Cities", "Rustboro City"}, -- Rustboro City
  [2816] = {"Cities", "Rustboro City"}, -- Rustboro City - Devon Corp 1F
  [2817] = {"Cities", "Rustboro City"}, -- Rustboro City - Devon Corp 2F
  [2818] = {"Cities", "Rustboro City"}, -- Rustboro City - Devon Corp 3F
  [2819] = {"Cities", "Rustboro Gym"}, -- Rustboro City - Gym
  [2820] = {"Cities", "Rustboro City"}, -- Rustboro City - Pokemon School
  [2821] = {"Cities", "Rustboro City"}, -- Rustboro City - Pokemon Center 1F
  [2822] = {"Cities", "Rustboro City"}, -- Rustboro City - Pokemon Center 2F
  [2823] = {"Cities", "Rustboro City"}, -- Rustboro City - Mart
  [2824] = {"Cities", "Rustboro City"}, -- Rustboro City - Flat 1 1F
  [2825] = {"Cities", "Rustboro City"}, -- Rustboro City - Flat 1 2F
  [2826] = {"Cities", "Rustboro City"}, -- Rustboro City - House 1
  [2827] = {"Cities", "Rustboro City"}, -- Rustboro City - Cutter's House
  [2828] = {"Cities", "Rustboro City"}, -- Rustboro City - House 2
  [2829] = {"Cities", "Rustboro City"}, -- Rustboro City - Flat 2 1F
  [2830] = {"Cities", "Rustboro City"}, -- Rustboro City - Flat 2 2F
  [2831] = {"Cities", "Rustboro City"}, -- Rustboro City - Flat 2 3F
  [2832] = {"Cities", "Rustboro City"}, -- Rustboro City - House 3
  [11] = {"Cities", "Dewford Town"}, -- Dewford Town
  [768] = {"Cities", "Dewford Town"}, -- Dewford Town - House 1
  [769] = {"Cities", "Dewford Town"}, -- Dewford Town - Pokemon Center 1F
  [770] = {"Cities", "Dewford Town"}, -- Dewford Town - Pokemon Center 2F
  [771] = {"Cities", "Dewford Gym"}, -- Dewford Town - Gym
  [772] = {"Cities", "Dewford Town"}, -- Dewford Town - Town Hall
  [773] = {"Cities", "Dewford Town"}, -- Dewford Town - House 2
  [1] = {"Cities", "Slateport City"}, -- Slateport City
  [2304] = {"Cities", "Slateport City"}, -- Slateport City - Stern's Shipyard 1F
  [2305] = {"Cities", "Slateport City"}, -- Slateport City - Stern's Shipyard 2F
  [2306] = {"Cities", "Slateport City"}, -- Slateport City - Battle Tent Lobby
  [2307] = {"Cities", "Slateport City"}, -- Slateport City - Battle Tent Corridor
  [2308] = {"Cities", "Slateport City"}, -- Slateport City - Battle Tent Room
  [2309] = {"Cities", "Slateport City"}, -- Slateport City - Name Rater's House
  [2310] = {"Cities", "Slateport City"}, -- Slateport City - Pokemon Fan Club
  [2311] = {"Cities", "Slateport City"}, -- Slateport City - Oceanic Museum 1F
  [2312] = {"Cities", "Slateport City"}, -- Slateport City - Oceanic Museum 2F
  [2313] = {"Cities", "Slateport City"}, -- Slateport City - Harbor
  [2314] = {"Cities", "Slateport City"}, -- Slateport City - House
  [2315] = {"Cities", "Slateport City"}, -- Slateport City - Pokemon Center 1F
  [2316] = {"Cities", "Slateport City"}, -- Slateport City - Pokemon Center 2F
  [2317] = {"Cities", "Slateport City"}, -- Slateport City - Mart
  [2] = {"Cities", "Mauville City"}, -- Mauville City
  [2560] = {"Cities", "Mauville Gym"}, -- Mauville City - Gym
  [2561] = {"Cities", "Mauville City"}, -- Mauville City - Bike Shop
  [2562] = {"Cities", "Mauville City"}, -- Mauville City - House 1
  [2563] = {"Cities", "Mauville City"}, -- Mauville City - Game Corner
  [2564] = {"Cities", "Mauville City"}, -- Mauville City - House 2
  [2565] = {"Cities", "Mauville City"}, -- Mauville City - Pokemon Center 1F
  [2566] = {"Cities", "Mauville City"}, -- Mauville City - Pokemon Center 2F
  [2567] = {"Cities", "Mauville City"}, -- Mauville City - Mart
  [13] = {"Cities", "Fallarbor Town"}, -- Fallarbor Town
  [1280] = {"Cities", "Fallarbor Town"}, -- Fallarbor Town - Mart
  [1281] = {"Cities", "Fallarbor Town"}, -- Fallarbor Town - Battle Tent Lobby
  [1282] = {"Cities", "Fallarbor Town"}, -- Fallarbor Town - Battle Tent Corridor
  [1283] = {"Cities", "Fallarbor Town"}, -- Fallarbor Town - Battle Tent Room
  [1284] = {"Cities", "Fallarbor Town"}, -- Fallarbor Town - Pokemon Center 1F
  [1285] = {"Cities", "Fallarbor Town"}, -- Fallarbor Town - Pokemon Center 2F
  [1286] = {"Cities", "Fallarbor Town"}, -- Fallarbor Town - Cozmo's House
  [1287] = {"Cities", "Fallarbor Town"}, -- Fallarbor Town - Move Relearner's House
  [12] = {"Cities", "Lavaridge Town"}, -- Lavaridge Town
  [1024] = {"Cities", "Lavaridge Town"}, -- Lavaridge Town - Herb Shop
  [1025] = {"Cities", "Lavaridge Gym"}, -- Lavaridge Town - Gym 1F
  [1026] = {"Cities", "Lavaridge Gym"}, -- Lavaridge Town - Gym B1F
  [1027] = {"Cities", "Lavaridge Town"}, -- Lavaridge Town - House
  [1028] = {"Cities", "Lavaridge Town"}, -- Lavaridge Town - Mart
  [1029] = {"Cities", "Lavaridge Town"}, -- Lavaridge Town - Pokemon Center 1F
  [1030] = {"Cities", "Lavaridge Town"}, -- Lavaridge Town - Pokemon Center 2F
  [14] = {"Cities", "Verdanturf Town"}, -- Verdanturf Town
  [1536] = {"Cities", "Verdanturf Town"}, -- Verdanturf Town - Battle Tent Lobby
  [1537] = {"Cities", "Verdanturf Town"}, -- Verdanturf Town - Battle Tent Corridor
  [1538] = {"Cities", "Verdanturf Town"}, -- Verdanturf Town - Battle Tent Room
  [1539] = {"Cities", "Verdanturf Town"}, -- Verdanturf Town - Mart
  [1540] = {"Cities", "Verdanturf Town"}, -- Verdanturf Town - Pokemon Center 1F
  [1541] = {"Cities", "Verdanturf Town"}, -- Verdanturf Town - Pokemon Center 2F
  [1542] = {"Cities", "Verdanturf Town"}, -- Verdanturf Town - Wanda's House
  [1543] = {"Cities", "Verdanturf Town"}, -- Verdanturf Town - Friendship Rater's House
  [1544] = {"Cities", "Verdanturf Town"}, -- Verdanturf Town - House
  [4] = {"Cities", "Fortree City"}, -- Fortree City
  [3072] = {"Cities", "Fortree City"}, -- Fortree City - House 1
  [3073] = {"Cities", "Fortree Gym"}, -- Fortree City - Gym
  [3081] = {"Cities", "Fortree City"}, -- Fortree City - Decoration Shop
  [3074] = {"Cities", "Fortree City"}, -- Fortree City - Pokemon Center 1F
  [3075] = {"Cities", "Fortree City"}, -- Fortree City - Pokemon Center 2F
  [3076] = {"Cities", "Fortree City"}, -- Fortree City - Mart
  [3077] = {"Cities", "Fortree City"}, -- Fortree City - House 2
  [3078] = {"Cities", "Fortree City"}, -- Fortree City - House 3
  [3079] = {"Cities", "Fortree City"}, -- Fortree City - House 4
  [3080] = {"Cities", "Fortree City"}, -- Fortree City - House 5
  [5] = {"Cities", "Lilycove City"}, -- Lilycove City
  [3328] = {"Cities", "Lilycove City"}, -- Lilycove City - Motel 1F
  [3329] = {"Cities", "Lilycove City"}, -- Lilycove City - Motel 2F
  [3330] = {"Cities", "Lilycove City"}, -- Lilycove City - Museum 1F
  [3331] = {"Cities", "Lilycove City"}, -- Lilycove City - Museum 2F
  [3332] = {"Cities", "Lilycove City"}, -- Lilycove City - Contest Lobby
  [3333] = {"Cities", "Lilycove City"}, -- Lilycove City - Contest Hall
  [3334] = {"Cities", "Lilycove City"}, -- Lilycove City - Pokemon Center 1F
  [3335] = {"Cities", "Lilycove City"}, -- Lilycove City - Pokemon Center 2F
  [3336] = {"Cities", "Lilycove City"}, -- Lilycove City - Unused Mart
  [3337] = {"Cities", "Lilycove City"}, -- Lilycove City - Pokemon Trainer Fan Club
  [3338] = {"Cities", "Lilycove City"}, -- Lilycove City - Harbor
  [3339] = {"Cities", "Lilycove City"}, -- Lilycove City - Move Deleter's House
  [3340] = {"Cities", "Lilycove City"}, -- Lilycove City - House 1
  [3341] = {"Cities", "Lilycove City"}, -- Lilycove City - House 2
  [3342] = {"Cities", "Lilycove City"}, -- Lilycove City - House 3
  [3343] = {"Cities", "Lilycove City"}, -- Lilycove City - House 4
  [3344] = {"Cities", "Lilycove City"}, -- Lilycove City - Department Store 1F
  [3345] = {"Cities", "Lilycove City"}, -- Lilycove City - Department Store 2F
  [3346] = {"Cities", "Lilycove City"}, -- Lilycove City - Department Store 3F
  [3347] = {"Cities", "Lilycove City"}, -- Lilycove City - Department Store 4F
  [3348] = {"Cities", "Lilycove City"}, -- Lilycove City - Department Store 5F
  [3349] = {"Cities", "Lilycove City"}, -- Lilycove City - Department Store Rooftop
  [3350] = {"Cities", "Lilycove City"}, -- Lilycove City - Department Store Elevator
  [6441] = {"Cities", "S.S. Tidal"}, --  S.S. Tidal - Corridor
  [6442] = {"Cities", "S.S. Tidal"}, --  S.S. Tidal - Lower Deck
  [6443] = {"Cities", "S.S. Tidal"}, --  S.S. Tidal - Rooms
  [6] = {"Cities", "Mossdeep City"}, -- Mossdeep City
  [3584] = {"Cities", "Mossdeep Gym"}, -- Mossdeep City - Gym
  [3585] = {"Cities", "Mossdeep City"}, -- Mossdeep City - House 1
  [3586] = {"Cities", "Mossdeep City"}, -- Mossdeep City - House 2
  [3587] = {"Cities", "Mossdeep City"}, -- Mossdeep City - Pokemon Center 1F
  [3588] = {"Cities", "Mossdeep City"}, -- Mossdeep City - Pokemon Center 2F
  [3589] = {"Cities", "Mossdeep City"}, -- Mossdeep City - Mart
  [3590] = {"Cities", "Mossdeep City"}, -- Mossdeep City - House 3
  [3591] = {"Cities", "Mossdeep City"}, -- Mossdeep City - Steven's House
  [3592] = {"Cities", "Mossdeep City"}, -- Mossdeep City - House 4
  [3593] = {"Cities", "Mossdeep City"}, -- Mossdeep City - Space Center 1F
  [3594] = {"Cities", "Mossdeep City"}, -- Mossdeep City - Space Center 2F
  [3595] = {"Cities", "Mossdeep City"}, -- Mossdeep City - Game Corner 1F
  [3596] = {"Cities", "Mossdeep City"}, -- Mossdeep City - Game Corner B1F
  [7] = {"Cities", "Sootopolis City"}, -- Sootopolis City
  [3840] = {"Cities", "Sootopolis Gym"}, -- Sootopolis City - Gym 1F
  [3841] = {"Cities", "Sootopolis Gym"}, -- Sootopolis City - Gym B1F
  [3842] = {"Cities", "Sootopolis City"}, -- Sootopolis City - Pokemon Center 1F
  [3843] = {"Cities", "Sootopolis City"}, -- Sootopolis City - Pokemon Center 2F
  [3844] = {"Cities", "Sootopolis City"}, -- Sootopolis City - Mart
  [3845] = {"Cities", "Sootopolis City"}, -- Sootopolis City - House 1
  [3846] = {"Cities", "Sootopolis City"}, -- Sootopolis City - House 2
  [3847] = {"Cities", "Sootopolis City"}, -- Sootopolis City - House 3
  [3848] = {"Cities", "Sootopolis City"}, -- Sootopolis City - House 4
  [3849] = {"Cities", "Sootopolis City"}, -- Sootopolis City - House 5
  [3850] = {"Cities", "Sootopolis City"}, -- Sootopolis City - House 6
  [3851] = {"Cities", "Sootopolis City"}, -- Sootopolis City - House 7
  [3852] = {"Cities", "Sootopolis City"}, -- Sootopolis City - Lotad & Seedot House
  [3853] = {"Cities", "Sootopolis City"}, -- Sootopolis City - Mystery Event's House 1F
  [3854] = {"Cities", "Sootopolis City"}, -- Sootopolis City - Mystery Event's House B1F
  [15] = {"Cities", "Pacifidlog Town"}, -- Pacifidlog Town
  [1792] = {"Cities", "Pacifidlog Town"}, -- Pacifidlog Town - Pokemon Center 1F
  [1793] = {"Cities", "Pacifidlog Town"}, -- Pacifidlog Town - Pokemon Center 2F
  [1794] = {"Cities", "Pacifidlog Town"}, -- Pacifidlog Town - House 1
  [1795] = {"Cities", "Pacifidlog Town"}, -- Pacifidlog Town - House 2
  [1796] = {"Cities", "Pacifidlog Town"}, -- Pacifidlog Town - House 3
  [1797] = {"Cities", "Pacifidlog Town"}, -- Pacifidlog Town - House 4
  [1798] = {"Cities", "Pacifidlog Town"}, -- Pacifidlog Town - House 5
  [8] = {"Cities", "Ever Grande City"}, -- Ever Grande City
  [4096] = {"Cities", "Ever Grande City"}, -- Ever Grande City - Sidney's Room
  [4097] = {"Cities", "Ever Grande City"}, -- Ever Grande City - Phoebe's Room
  [4098] = {"Cities", "Ever Grande City"}, -- Ever Grande City - Glacia's Room
  [4099] = {"Cities", "Ever Grande City"}, -- Ever Grande City - Drake's Room
  [4100] = {"Cities", "Ever Grande City"}, -- Ever Grande City - Champion's Room
  [4101] = {"Cities", "Ever Grande City"}, -- Ever Grande City - Hall 1
  [4102] = {"Cities", "Ever Grande City"}, -- Ever Grande City - Hall 2
  [4103] = {"Cities", "Ever Grande City"}, -- Ever Grande City - Hall 3
  [4104] = {"Cities", "Ever Grande City"}, -- Ever Grande City - Hall 4
  [4105] = {"Cities", "Ever Grande City"}, -- Ever Grande City - Hall 5
  [4106] = {"Cities", "Ever Grande City"}, -- Ever Grande City - Pokemon League 1F
  [4107] = {"Cities", "Ever Grande City"}, -- Ever Grande City - Hall of Fame
  [4108] = {"Cities", "Ever Grande City"}, -- Ever Grande City - Pokemon Center 1F
  [4109] = {"Cities", "Ever Grande City"}, -- Ever Grande City - Pokemon Center 2F
  [4110] = {"Cities", "Ever Grande City"}, -- Ever Grande City - Pokemon League 2F
  -- [6155] = {"Dungeons", "Petalburg Woods"}, -- Petalburg Woods
  -- [6148] = {"Dungeons", "Rusturf Tunnel"}, -- Rusturf Tunnel
  [6151] = {"Dungeons", "Granite Cave"}, -- Granite Cave 1F
  [6152] = {"Dungeons", "Granite Cave"}, -- Granite Cave B1F
  [6153] = {"Dungeons", "Granite Cave"}, -- Granite Cave B2F
  [6154] = {"Dungeons", "Granite Cave"}, -- Granite Cave - Steven's Room
  -- [6158] = {"Dungeons", "Fiery Path"}, -- Fiery Path
  [6144] = {"Dungeons", "Meteor Falls"}, -- Meteor Falls 1F-1R
  [6145] = {"Dungeons", "Meteor Falls"}, -- Meteor Falls 1F-2R
  [6146] = {"Dungeons", "Meteor Falls"}, -- Meteor Falls B1F-1R
  [6147] = {"Dungeons", "Meteor Falls"}, -- Meteor Falls B1F-2R
  [6251] = {"Dungeons", "Meteor Falls"}, -- Meteor Falls - Steven's Cave
  -- [6196] = {"Dungeons", "New Mauville"}, -- New Mauville - Entrance
  -- [6197] = {"Dungeons", "New Mauville"}, -- New Mauville - Inside
  [6198] = {"Dungeons", "Abandoned Ship"}, -- Abandoned Ship - Deck
  [6199] = {"Dungeons", "Abandoned Ship"}, -- Abandoned Ship - Corridors 1F
  [6200] = {"Dungeons", "Abandoned Ship"}, -- Abandoned Ship - Rooms 1F
  [6201] = {"Dungeons", "Abandoned Ship"}, -- Abandoned Ship - Corridors B1F
  [6202] = {"Dungeons", "Abandoned Ship"}, -- Abandoned Ship - Rooms B1F
  [6203] = {"Dungeons", "Abandoned Ship"}, -- Abandoned Ship - Rooms 2 B1F
  [6204] = {"Dungeons", "Abandoned Ship"}, -- Abandoned Ship - Underwater 1
  [6205] = {"Dungeons", "Abandoned Ship"}, -- Abandoned Ship - Room B1F
  [6206] = {"Dungeons", "Abandoned Ship"}, -- Abandoned Ship - Rooms 2 1F
  [6207] = {"Dungeons", "Abandoned Ship"}, -- Abandoned Ship - Captain's Office
  [6208] = {"Dungeons", "Abandoned Ship"}, -- Abandoned Ship - Underwater 2
  [6209] = {"Dungeons", "Abandoned Ship"}, -- Abandoned Ship - Hidden Floor Corridors
  [6210] = {"Dungeons", "Abandoned Ship"}, -- Abandoned Ship - Hidden Floor Rooms
  [6159] = {"Dungeons", "Mt. Pyre Interior"}, -- Mt. Pyre 1F
  [6160] = {"Dungeons", "Mt. Pyre Interior"}, -- Mt. Pyre 2F
  [6161] = {"Dungeons", "Mt. Pyre Interior"}, -- Mt. Pyre 3F
  [6162] = {"Dungeons", "Mt. Pyre Interior"}, -- Mt. Pyre 4F
  [6163] = {"Dungeons", "Mt. Pyre Interior"}, -- Mt. Pyre 5F
  [6164] = {"Dungeons", "Mt. Pyre Interior"}, -- Mt. Pyre 6F
  [6165] = {"Dungeons", "Mt. Pyre Exterior"}, -- Mt. Pyre Exterior
  [6166] = {"Dungeons", "Mt. Pyre Exterior"}, -- Mt. Pyre Summit
  [6230] = {"Dungeons", "Magma Hideout"}, -- Magma Hideout 1F
  [6231] = {"Dungeons", "Magma Hideout"}, -- Magma Hideout 2F-1R
  [6232] = {"Dungeons", "Magma Hideout"}, -- Magma Hideout 2F-2R
  [6233] = {"Dungeons", "Magma Hideout"}, -- Magma Hideout 3F-1R
  [6234] = {"Dungeons", "Magma Hideout"}, -- Magma Hideout 3F-2R
  [6235] = {"Dungeons", "Magma Hideout"}, -- Magma Hideout 4F
  [6236] = {"Dungeons", "Magma Hideout"}, -- Magma Hideout 3F-3R
  [6237] = {"Dungeons", "Magma Hideout"}, -- Magma Hideout 2F-3R
  [6167] = {"Dungeons", "Aqua Hideout"}, -- Aqua Hideout 1F
  [6168] = {"Dungeons", "Aqua Hideout"}, -- Aqua Hideout B1F
  [6169] = {"Dungeons", "Aqua Hideout"}, -- Aqua Hideout B2F
  [6190] = {"Dungeons", "Shoal Cave"}, -- Shoal Cave Low Tide - Entrance Room
  [6191] = {"Dungeons", "Shoal Cave"}, -- Shoal Cave Low Tide - Inner Room
  [6192] = {"Dungeons", "Shoal Cave"}, -- Shoal Cave Low Tide - Stairs Room
  [6193] = {"Dungeons", "Shoal Cave"}, -- Shoal Cave Low Tide - Lower Room
  [6194] = {"Dungeons", "Shoal Cave"}, -- Shoal Cave High Tide - Entrance Room
  [6195] = {"Dungeons", "Shoal Cave"}, -- Shoal Cave High Tide - Inner Room
  [6227] = {"Dungeons", "Shoal Cave"}, -- Shoal Cave Low Tide - Ice Room
  [6171] = {"Dungeons", "Seafloor Cavern"}, -- Seafloor Cavern - Entrance
  [6172] = {"Dungeons", "Seafloor Cavern"}, -- Seafloor Cavern - Room 1
  [6173] = {"Dungeons", "Seafloor Cavern"}, -- Seafloor Cavern - Room 2
  [6174] = {"Dungeons", "Seafloor Cavern"}, -- Seafloor Cavern - Room 3
  [6175] = {"Dungeons", "Seafloor Cavern"}, -- Seafloor Cavern - Room 4
  [6176] = {"Dungeons", "Seafloor Cavern"}, -- Seafloor Cavern - Room 5
  [6177] = {"Dungeons", "Seafloor Cavern"}, -- Seafloor Cavern - Room 6
  [6178] = {"Dungeons", "Seafloor Cavern"}, -- Seafloor Cavern - Room 7
  [6179] = {"Dungeons", "Seafloor Cavern"}, -- Seafloor Cavern - Room 8
  [6180] = {"Dungeons", "Seafloor Cavern"}, -- Seafloor Cavern - Room 9
  [6187] = {"Dungeons", "Victory Road"}, -- Victory Road 1F
  [6188] = {"Dungeons", "Victory Road"}, -- Victory Road B1F
  [6189] = {"Dungeons", "Victory Road"}, -- Victory Road B2F
  [6243] = {"Dungeons", "Artisan Cave"}, -- Artisan Cave B1F
  [6244] = {"Dungeons", "Artisan Cave"}, -- Artisan Cave 1F
  [6212] = {"Dungeons", "Ancient Tomb"}, -- Ancient Tomb
  -- [6181] = {"Dungeons", "Cave of Origin"}, -- Cave of Origin - Entrance
  -- [6182] = {"Dungeons", "Cave of Origin"}, -- Cave of Origin 1F
  -- [6186] = {"Dungeons", "Cave of Origin"}, -- Cave of Origin B1F
  -- [6150] = {"Dungeons", "Desert Ruins"}, -- Desert Ruins
  -- [6242] = {"Dungeons", "Desert Underpass"}, -- Desert Underpass
  -- [6211] = {"Dungeons", "Island Cave"}, -- Island Cave
  -- [6246] = {"Dungeons", "Marine Cave"}, -- Marine Cave - Entrance
  -- [6247] = {"Dungeons", "Marine Cave"}, -- Marine Cave - End
  -- [6238] = {"Dungeons", "Mirage Tower"}, -- Mirage Tower 1F
  -- [6239] = {"Dungeons", "Mirage Tower"}, -- Mirage Tower 2F
  -- [6240] = {"Dungeons", "Mirage Tower"}, -- Mirage Tower 3F
  -- [6241] = {"Dungeons", "Mirage Tower"}, -- Mirage Tower 4F
  -- [6215] = {"Dungeons", "Sealed Chamber"}, -- Sealed Chamber - Outer Room
  -- [6216] = {"Dungeons", "Sealed Chamber"}, -- Sealed Chamber - Inner Room
  -- [6221] = {"Dungeons", "Sky Pillar"}, -- Sky Pillar - Entrance
  -- [6222] = {"Dungeons", "Sky Pillar"}, -- Sky Pillar - Outside
  -- [6223] = {"Dungeons", "Sky Pillar"}, -- Sky Pillar 1F
  -- [6224] = {"Dungeons", "Sky Pillar"}, -- Sky Pillar 2F
  -- [6225] = {"Dungeons", "Sky Pillar"}, -- Sky Pillar 3F
  -- [6226] = {"Dungeons", "Sky Pillar"}, -- Sky Pillar 4F
  -- [6228] = {"Dungeons", "Sky Pillar"}, -- Sky Pillar 5F
  -- [6229] = {"Dungeons", "Sky Pillar"}, -- Sky Pillar - Top
  -- [6248] = {"Dungeons", "Terra Cave"}, -- Terra Cave - Entrance
  -- [6249] = {"Dungeons", "Terra Cave"}, -- Terra Cave - End
  -- [6665] = {"Islands", "Southern Island"}, -- Southern Island - Exterior
  -- [6666] = {"Islands", "Southern Island"}, -- Southern Island - Interior
  -- [6712] = {"Islands", "Faraway Island"}, -- Faraway Island - Entrance
  -- [6713] = {"Islands", "Faraway Island"}, -- Faraway Island - Interior
  -- [6714] = {"Islands", "Birth Island"}, -- Birth Island - Exterior
  -- [6715] = {"Islands", "Birth Island"}, -- Birth Island - Harbor
  -- [6722] = {"Islands", "Navel Rock"}, -- Navel Rock - Exterior
  -- [6723] = {"Islands", "Navel Rock"}, -- Navel Rock - Harbor
  -- [6724] = {"Islands", "Navel Rock"}, -- Navel Rock - Entrance
  -- [6725] = {"Islands", "Navel Rock"}, -- Navel Rock B1F
  -- [6726] = {"Islands", "Navel Rock"}, -- Navel Rock - Fork
  -- [6727] = {"Islands", "Navel Rock"}, -- Navel Rock - Up 1
  -- [6728] = {"Islands", "Navel Rock"}, -- Navel Rock - Up 2
  -- [6729] = {"Islands", "Navel Rock"}, -- Navel Rock - Up 3
  -- [6730] = {"Islands", "Navel Rock"}, -- Navel Rock - Up 4
  -- [6731] = {"Islands", "Navel Rock"}, -- Navel Rock - Top
  -- [6732] = {"Islands", "Navel Rock"}, -- Navel Rock - Down 1
  -- [6733] = {"Islands", "Navel Rock"}, -- Navel Rock - Down 2
  -- [6734] = {"Islands", "Navel Rock"}, -- Navel Rock - Down 3
  -- [6735] = {"Islands", "Navel Rock"}, -- Navel Rock - Down 4
  -- [6736] = {"Islands", "Navel Rock"}, -- Navel Rock - Down 5
  -- [6737] = {"Islands", "Navel Rock"}, -- Navel Rock - Down 6
  -- [6738] = {"Islands", "Navel Rock"}, -- Navel Rock - Down 7
  -- [6739] = {"Islands", "Navel Rock"}, -- Navel Rock - Down 8
  -- [6740] = {"Islands", "Navel Rock"}, -- Navel Rock - Down 9
  -- [6741] = {"Islands", "Navel Rock"}, -- Navel Rock - Down 10
  -- [6742] = {"Islands", "Navel Rock"}, -- Navel Rock - Down 11
  -- [6743] = {"Islands", "Navel Rock"}, -- Navel Rock - Bottom
  [16] = {"Routes", "Route 101"}, -- Route 101
  [17] = {"Routes", "Route 102"}, -- Route 102
  [18] = {"Routes", "Route 103"}, -- Route 103
  [19] = {"Routes", "Route 104"}, -- Route 104
  [4352] = {"Routes", "Route 104"}, -- Route 104 - Mr. Briney's House
  [4353] = {"Routes", "Route 104"}, -- Route 104 - Pretty Petal Flower Shop
  [20] = {"Routes", "Route 105"}, -- Route 105
  [21] = {"Routes", "Route 106"}, -- Route 106
  [22] = {"Routes", "Route 107"}, -- Route 107
  [23] = {"Routes", "Route 108"}, -- Route 108
  [24] = {"Routes", "Route 109"}, -- Route 109
  [7168] = {"Routes", "Route 109"}, -- Route 109 - Seahorse House
  [25] = {"Routes", "Route 110"}, -- Route 110
  [7435] = {"Routes", "Route 110"}, -- Route 110 - Seaside Cycling Road North Entrance
  [7436] = {"Routes", "Route 110"}, -- Route 110 - Seaside Cycling Road South Entrance
  -- [7424] = {"Routes", "Trick House"}, -- Trick House - Entrance
  -- [7425] = {"Routes", "Trick House"}, -- Trick House - End
  -- [7426] = {"Routes", "Trick House"}, -- Trick House - Corridor
  -- [7427] = {"Routes", "Trick House"}, -- Trick House - Puzzle 1
  -- [7428] = {"Routes", "Trick House"}, -- Trick House - Puzzle 2
  -- [7429] = {"Routes", "Trick House"}, -- Trick House - Puzzle 3
  -- [7430] = {"Routes", "Trick House"}, -- Trick House - Puzzle 4
  -- [7431] = {"Routes", "Trick House"}, -- Trick House - Puzzle 5
  -- [7432] = {"Routes", "Trick House"}, -- Trick House - Puzzle 6
  -- [7433] = {"Routes", "Trick House"}, -- Trick House - Puzzle 7
  -- [7434] = {"Routes", "Trick House"}, -- Trick House - Puzzle 8
  [26] = {"Routes", "Route 111"}, -- Route 111
  [4608] = {"Routes", "Route 111"}, -- Route 111 - Winstrate Family's House
  [4609] = {"Routes", "Route 111"}, -- Route 111 - Old Lady's Rest Stop
  [27] = {"Routes", "Route 112"}, -- Route 112
  [4864] = {"Routes", "Route 112"}, -- Route 112 - Cable Car Station
  [28] = {"Routes", "Route 113"}, -- Route 113
  [7680] = {"Routes", "Route 113"}, -- Route 113 - Glass Workshop
  [29] = {"Routes", "Route 114"}, -- Route 114
  [5120] = {"Routes", "Route 114"}, -- Route 114 - Fossil Maniac's House
  [5121] = {"Routes", "Route 114"}, -- Route 114 - Fossil Maniac's Tunnel
  [5122] = {"Routes", "Route 114"}, -- Route 114 - Lanette's House
  [30] = {"Routes", "Route 115"}, -- Route 115
  [31] = {"Routes", "Route 116"}, -- Route 116
  [5376] = {"Routes", "Route 116"}, -- Route 116 - Tunneler's Rest House
  [32] = {"Routes", "Route 117"}, -- Route 117
  [5632] = {"Routes", "Route 117"}, -- Route 117 - Pokemon Daycare
  [33] = {"Routes", "Route 118"}, -- Route 118
  [34] = {"Routes", "Route 119"}, -- Route 119
  [8194] = {"Routes", "Route 119"}, -- Route 119 - House
  [8192] = {"Routes", "Weather Institute"}, -- Weather Institute 1F
  [8193] = {"Routes", "Weather Institute"}, -- Weather Institute 2F
  [35] = {"Routes", "Route 120"}, -- Route 120
  [6217] = {"Routes", "Route 120"}, -- Route 120 - Scorched Slab
  [36] = {"Routes", "Route 121"}, -- Route 121
  [37] = {"Routes", "Route 122"}, -- Route 122
  [38] = {"Routes", "Route 123"}, -- Route 123
  [7936] = {"Routes", "Route 123"}, -- Route 123 - Berry Master's House
  [39] = {"Routes", "Route 124"}, -- Route 124
  [8448] = {"Routes", "Route 124"}, -- Route 124 - Diving Treasure Hunter's House
  [40] = {"Routes", "Route 125"}, -- Route 125
  [41] = {"Routes", "Route 126"}, -- Route 126
  [42] = {"Routes", "Route 127"}, -- Route 127
  [43] = {"Routes", "Route 128"}, -- Route 128
  [44] = {"Routes", "Route 129"}, -- Route 129
  [45] = {"Routes", "Route 130"}, -- Route 130
  [46] = {"Routes", "Route 131"}, -- Route 131
  [47] = {"Routes", "Routes 132-134"}, -- Route 132
  [48] = {"Routes", "Routes 132-134"}, -- Route 133
  [49] = {"Routes", "Routes 132-134"}, -- Route 134
  -- [6156] = {"Routes", "Mt. Chimney"}, -- Mt. Chimney
  -- [4865] = {"Routes", "Mt. Chimney"}, -- Mt. Chimney - Cable Car Station
  -- [6157] = {"Routes", "Jagged Pass"}, -- Jagged Pass
  [5888] = {"Dungeons", "Safari Zone"}, -- Safari Zone - Entrance
  [6656] = {"Dungeons", "Safari Zone"}, -- Safari Zone - Northwest
  [6657] = {"Dungeons", "Safari Zone"}, -- Safari Zone - North
  [6658] = {"Dungeons", "Safari Zone"}, -- Safari Zone - Southwest
  [6659] = {"Dungeons", "Safari Zone"}, -- Safari Zone - South
  [6667] = {"Dungeons", "Safari Zone"}, -- Safari Zone - Rest House
  [6668] = {"Dungeons", "Safari Zone"}, -- Safari Zone - Northeast
  [6669] = {"Dungeons", "Safari Zone"}, -- Safari Zone - Southeast
}