TAB_MAPPING =
{
  [9] = {"Cities", "Western Cities", "Littleroot", "Littleroot Town"}, -- Littleroot Town
  [256] = {"Cities", "Western Cities", "Littleroot", "Brendan's House", "Brendan's House 1F"}, -- Littleroot Town - Brenden's House 1F
  [257] = {"Cities", "Western Cities", "Littleroot", "Brendan's House", "Brendan's House 2F"}, -- Littleroot Town - Brenden's House 2F
  [258] = {"Cities", "Western Cities", "Littleroot", "May's House", "May's House 1F"}, -- Littleroot Town - May's House 1F
  [259] = {"Cities", "Western Cities", "Littleroot", "May's House", "May's House 2F"}, -- Littleroot Town - May's House 2F
  [260] = {"Cities", "Western Cities", "Littleroot", "Professor Birch's Lab"}, -- Littleroot Town - Professor Birch's Lab
  [10] = {"Cities", "Western Cities", "Oldale", "Oldale Town"}, -- Oldale Town
  [512] = {"Cities", "Western Cities", "Oldale", "House 1"}, -- Oldale Town - House 1
  [513] = {"Cities", "Western Cities", "Oldale", "House 2"}, -- Oldale Town - House 2
  [514] = {"Cities", "Western Cities", "Oldale", "Pokemon Center", "Pokemon Center 1F"}, -- Oldale Town - Pokemon Center 1F
  [515] = {"Cities", "Western Cities", "Oldale", "Center", "Pokemon Center 2F"}, -- Oldale Town - Pokemon Center 2F
  [516] = {"Cities", "Western Cities", "Oldale", "Mart"}, -- Oldale Town - Mart
  [0] = {"Cities", "Western Cities", "Petalburg", "Petalburg City"}, -- Petalburg City
  [2048] = {"Cities", "Western Cities", "Petalburg", "Wally's House"}, -- Petalburg City - Wally's House
  [2049] = {"Cities", "Western Cities", "Petalburg", "Gym"}, -- Petalburg City - Gym
  [2050] = {"Cities", "Western Cities", "Petalburg", "House 1"}, -- Petalburg City - House 1
  [2051] = {"Cities", "Western Cities", "Petalburg", "House 2"}, -- Petalburg City - House 2
  [2052] = {"Cities", "Western Cities", "Petalburg", "Pokemon Center", "Pokemon Center 1F"}, -- Petalburg City - Pokemon Center 1F
  [2053] = {"Cities", "Western Cities", "Petalburg", "Pokemon Center", "Pokemon Center 2F"}, -- Petalburg City - Pokemon Center 2F
  [2054] = {"Cities", "Western Cities", "Petalburg", "Mart"}, -- Petalburg City - Mart
  [3] = {"Cities", "Western Cities", "Rustboro", "Rustboro City"}, -- Rustboro City
  [2816] = {"Cities", "Western Cities", "Rustboro", "Devon Corp", "Devon Corp 1F"}, -- Rustboro City - Devon Corp 1F
  [2817] = {"Cities", "Western Cities", "Rustboro", "Devon Corp", "Devon Corp 2F"}, -- Rustboro City - Devon Corp 2F
  [2818] = {"Cities", "Western Cities", "Rustboro", "Devon Corp", "Devon Corp 3F"}, -- Rustboro City - Devon Corp 3F
  [2819] = {"Cities", "Western Cities", "Rustboro", "Gym"}, -- Rustboro City - Gym
  [2820] = {"Cities", "Western Cities", "Rustboro", "Pokemon School"}, -- Rustboro City - Pokemon School
  [2821] = {"Cities", "Western Cities", "Rustboro", "Pokemon Center", "Pokemon Center 1F"}, -- Rustboro City - Pokemon Center 1F
  [2822] = {"Cities", "Western Cities", "Rustboro", "Pokemon Center", "Pokemon Center 2F"}, -- Rustboro City - Pokemon Center 2F
  [2823] = {"Cities", "Western Cities", "Rustboro", "Mart"}, -- Rustboro City - Mart
  [2824] = {"Cities", "Western Cities", "Rustboro", "Houses", "Flat 1", "Flat 1 1F"}, -- Rustboro City - Flat 1 1F
  [2825] = {"Cities", "Western Cities", "Rustboro", "Houses", "Flat 1", "Flat 1 2F"}, -- Rustboro City - Flat 1 2F
  [2826] = {"Cities", "Western Cities", "Rustboro", "Houses", "House 1"}, -- Rustboro City - House 1
  [2827] = {"Cities", "Western Cities", "Rustboro", "Cutter's House"}, -- Rustboro City - Cutter's House
  [2828] = {"Cities", "Western Cities", "Rustboro", "Houses", "House 2"}, -- Rustboro City - House 2
  [2829] = {"Cities", "Western Cities", "Rustboro", "Houses", "Flat 2", "Flat 2 1F"}, -- Rustboro City - Flat 2 1F
  [2830] = {"Cities", "Western Cities", "Rustboro", "Houses", "Flat 2", "Flat 2 2F"}, -- Rustboro City - Flat 2 2F
  [2831] = {"Cities", "Western Cities", "Rustboro", "Houses", "Flat 2", "Flat 2 3F"}, -- Rustboro City - Flat 2 3F
  [2832] = {"Cities", "Western Cities", "Rustboro", "Houses", "House 3"}, -- Rustboro City - House 3
  [11] = {"Cities", "Western Cities", "Dewford", "Dewford Town"}, -- Dewford Town
  [768] = {"Cities", "Western Cities", "Dewford", "House 1"}, -- Dewford Town - House 1
  [769] = {"Cities", "Western Cities", "Dewford", "Pokemon Center", "Pokemon Center 1F"}, -- Dewford Town - Pokemon Center 1F
  [770] = {"Cities", "Western Cities", "Dewford", "Pokemon Center", "Pokemon Center 2F"}, -- Dewford Town - Pokemon Center 2F
  [771] = {"Cities", "Western Cities", "Dewford", "Gym"}, -- Dewford Town - Gym
  [772] = {"Cities", "Western Cities", "Dewford", "Dewford Hall"}, -- Dewford Town - Town Hall
  [773] = {"Cities", "Western Cities", "Dewford", "House 2"}, -- Dewford Town - House 2
  [1] = {"Cities", "Western Cities", "Slateport", "Slateport City"}, -- Slateport City
  [2304] = {"Cities", "Western Cities", "Slateport", "Shipyard", "Slateport Shipyard 1F"}, -- Slateport City - Stern's Shipyard 1F
  [2305] = {"Cities", "Western Cities", "Slateport", "Shipyard", "Slateport Shipyard 2F"}, -- Slateport City - Stern's Shipyard 2F
  [2306] = {"Cities", "Western Cities", "Slateport", "Battle Tent", "Lobby"}, -- Slateport City - Battle Tent Lobby
  [2307] = {"Cities", "Western Cities", "Slateport", "Battle Tent", "Corridor"}, -- Slateport City - Battle Tent Corridor
  [2308] = {"Cities", "Western Cities", "Slateport", "Battle Tent", "Room"}, -- Slateport City - Battle Tent Room
  [2309] = {"Cities", "Western Cities", "Slateport", "Name Rater's House"}, -- Slateport City - Name Rater's House
  [2310] = {"Cities", "Western Cities", "Slateport", "Pokemon Fan Club"}, -- Slateport City - Pokemon Fan Club
  [2311] = {"Cities", "Western Cities", "Slateport", "Oceanic Museum", "Oceanic Museum 1F"}, -- Slateport City - Oceanic Museum 1F
  [2312] = {"Cities", "Western Cities", "Slateport", "Oceanic Museum", "Oceanic Museum 2F"}, -- Slateport City - Oceanic Museum 2F
  [2313] = {"Cities", "Western Cities", "Slateport", "Slateport Harbor"}, -- Slateport City - Harbor
  [2314] = {"Cities", "Western Cities", "Slateport", "House"}, -- Slateport City - House
  [2315] = {"Cities", "Western Cities", "Slateport", "Pokemon Center", "Pokemon Center 1F"}, -- Slateport City - Pokemon Center 1F
  [2316] = {"Cities", "Western Cities", "Slateport", "Pokemon Center", "Pokemon Center 2F"}, -- Slateport City - Pokemon Center 2F
  [2317] = {"Cities", "Western Cities", "Slateport", "Mart"}, -- Slateport City - Mart
  [2] = {"Cities", "Western Cities", "Mauville", "Mauville City"}, -- Mauville City
  [2560] = {"Cities", "Western Cities", "Mauville", "Gym"}, -- Mauville City - Gym
  [2561] = {"Cities", "Western Cities", "Mauville", "Bike Shop"}, -- Mauville City - Bike Shop
  [2562] = {"Cities", "Western Cities", "Mauville", "House 1"}, -- Mauville City - House 1
  [2563] = {"Cities", "Western Cities", "Mauville", "Game Corner"}, -- Mauville City - Game Corner
  [2564] = {"Cities", "Western Cities", "Mauville", "House 2"}, -- Mauville City - House 2
  [2565] = {"Cities", "Western Cities", "Mauville", "Pokemon Center", "Pokemon Center 1F"}, -- Mauville City - Pokemon Center 1F
  [2566] = {"Cities", "Western Cities", "Mauville", "Pokemon Center", "Pokemon Center 2F"}, -- Mauville City - Pokemon Center 2F
  [2567] = {"Cities", "Western Cities", "Mauville", "Mart"}, -- Mauville City - Mart
  [13] = {"Cities", "Western Cities", "Fallarbor", "Fallarbor Town"}, -- Fallarbor Town
  [1280] = {"Cities", "Western Cities", "Fallarbor", "Mart"}, -- Fallarbor Town - Mart
  [1281] = {"Cities", "Western Cities", "Fallarbor", "Battle Tent", "Lobby"}, -- Fallarbor Town - Battle Tent Lobby
  [1282] = {"Cities", "Western Cities", "Fallarbor", "Battle Tent", "Corridor"}, -- Fallarbor Town - Battle Tent Corridor
  [1283] = {"Cities", "Western Cities", "Fallarbor", "Battle Tent", "Room"}, -- Fallarbor Town - Battle Tent Room
  [1284] = {"Cities", "Western Cities", "Fallarbor", "Pokemon Center", "Pokemon Center 1F"}, -- Fallarbor Town - Pokemon Center 1F
  [1285] = {"Cities", "Western Cities", "Fallarbor", "Pokemon Center", "Pokemon Center 2F"}, -- Fallarbor Town - Pokemon Center 2F
  [1286] = {"Cities", "Western Cities", "Fallarbor", "Cosmo's House"}, -- Fallarbor Town - Cozmo's House
  [1287] = {"Cities", "Western Cities", "Fallarbor", "Move Tutor"}, -- Fallarbor Town - Move Relearner's House
  [12] = {"Cities", "Western Cities", "Lavaridge", "Lavaridge Town"}, -- Lavaridge Town
  [1024] = {"Cities", "Western Cities", "Lavaridge", "Herb Shop"}, -- Lavaridge Town - Herb Shop
  [1025] = {"Cities", "Western Cities", "Lavaridge", "Gym", "Gym 1F"}, -- Lavaridge Town - Gym 1F
  [1026] = {"Cities", "Western Cities", "Lavaridge", "Gym", "Gym B1F"}, -- Lavaridge Town - Gym B1F
  [1027] = {"Cities", "Western Cities", "Lavaridge", "House"}, -- Lavaridge Town - House
  [1028] = {"Cities", "Western Cities", "Lavaridge", "Mart"}, -- Lavaridge Town - Mart
  [1029] = {"Cities", "Western Cities", "Lavaridge", "Pokemon Center", "Pokemon Center 1F"}, -- Lavaridge Town - Pokemon Center 1F
  [1030] = {"Cities", "Western Cities", "Lavaridge", "Pokemon Center", "Pokemon Center 2F"}, -- Lavaridge Town - Pokemon Center 2F
  [14] = {"Cities", "Western Cities", "Verdanturf", "Verdanturf Town"}, -- Verdanturf Town
  [1536] = {"Cities", "Western Cities", "Verdanturf", "Battle Tent", "Lobby"}, -- Verdanturf Town - Battle Tent Lobby
  [1537] = {"Cities", "Western Cities", "Verdanturf", "Battle Tent", "Corridor"}, -- Verdanturf Town - Battle Tent Corridor
  [1538] = {"Cities", "Western Cities", "Verdanturf", "Battle Tent", "Room"}, -- Verdanturf Town - Battle Tent Room
  [1539] = {"Cities", "Western Cities", "Verdanturf", "Mart"}, -- Verdanturf Town - Mart
  [1540] = {"Cities", "Western Cities", "Verdanturf", "Pokemon Center", "Pokemon Center 1F"}, -- Verdanturf Town - Pokemon Center 1F
  [1541] = {"Cities", "Western Cities", "Verdanturf", "Pokemon Center", "Pokemon Center 2F"}, -- Verdanturf Town - Pokemon Center 2F
  [1542] = {"Cities", "Western Cities", "Verdanturf", "Wanda's House"}, -- Verdanturf Town - Wanda's House
  [1543] = {"Cities", "Western Cities", "Verdanturf", "Friendship Rater's House"}, -- Verdanturf Town - Friendship Rater's House
  [1544] = {"Cities", "Western Cities", "Verdanturf", "House"}, -- Verdanturf Town - House
  [4] = {"Cities", "Eastern Cities", "Fortree", "Fortree City"}, -- Fortree City
  [3072] = {"Cities", "Eastern Cities", "Fortree", "Houses", "House 1"}, -- Fortree City - House 1
  [3073] = {"Cities", "Eastern Cities", "Fortree", "Gym"}, -- Fortree City - Gym
  [3081] = {"Cities", "Eastern Cities", "Fortree", "Decoration Shop"}, -- Fortree City - Decoration Shop
  [3074] = {"Cities", "Eastern Cities", "Fortree", "Pokemon Center", "Pokemon Center 1F"}, -- Fortree City - Pokemon Center 1F
  [3075] = {"Cities", "Eastern Cities", "Fortree", "Pokemon Center", "Pokemon Center 2F"}, -- Fortree City - Pokemon Center 2F
  [3076] = {"Cities", "Eastern Cities", "Fortree", "Mart"}, -- Fortree City - Mart
  [3077] = {"Cities", "Eastern Cities", "Fortree", "Houses", "House 2"}, -- Fortree City - House 2
  [3078] = {"Cities", "Eastern Cities", "Fortree", "Houses", "House 3"}, -- Fortree City - House 3
  [3079] = {"Cities", "Eastern Cities", "Fortree", "Houses", "House 4"}, -- Fortree City - House 4
  [3080] = {"Cities", "Eastern Cities", "Fortree", "Houses", "House 5"}, -- Fortree City - House 5
  [5] = {"Cities", "Eastern Cities", "Lilycove", "Lilycove City"}, -- Lilycove City
  [3328] = {"Cities", "Eastern Cities", "Lilycove", "Motel", "1F"}, -- Lilycove City - Motel 1F
  [3329] = {"Cities", "Eastern Cities", "Lilycove", "Motel", "2F"}, -- Lilycove City - Motel 2F
  [3330] = {"Cities", "Eastern Cities", "Lilycove", "Museum", "1F"}, -- Lilycove City - Museum 1F
  [3331] = {"Cities", "Eastern Cities", "Lilycove", "Museum", "2F"}, -- Lilycove City - Museum 2F
  [3332] = {"Cities", "Eastern Cities", "Lilycove", "Contest Hall", "Lobby"}, -- Lilycove City - Contest Lobby
  [3333] = {"Cities", "Eastern Cities", "Lilycove", "Contest Hall", "Hall"}, -- Lilycove City - Contest Hall
  [3334] = {"Cities", "Eastern Cities", "Lilycove", "Pokemon Center", "Pokemon Center 1F"}, -- Lilycove City - Pokemon Center 1F
  [3335] = {"Cities", "Eastern Cities", "Lilycove", "Pokemon Center", "Pokemon Center 2F"}, -- Lilycove City - Pokemon Center 2F
  [3336] = {"Cities", "Eastern Cities", "Lilycove"}, -- Lilycove City - Unused Mart
  [3337] = {"Cities", "Eastern Cities", "Lilycove", "Trainer Fan Club"}, -- Lilycove City - Pokemon Trainer Fan Club
  [3338] = {"Cities", "Eastern Cities", "Lilycove", "Lilycove Harbor"}, -- Lilycove City - Harbor
  [3339] = {"Cities", "Eastern Cities", "Lilycove", "Move Deleter's House"}, -- Lilycove City - Move Deleter's House
  [3340] = {"Cities", "Eastern Cities", "Lilycove", "Houses", "House 1"}, -- Lilycove City - House 1
  [3341] = {"Cities", "Eastern Cities", "Lilycove", "Houses", "House 2"}, -- Lilycove City - House 2
  [3342] = {"Cities", "Eastern Cities", "Lilycove", "Houses", "House 3"}, -- Lilycove City - House 3
  [3343] = {"Cities", "Eastern Cities", "Lilycove", "Houses", "House 4"}, -- Lilycove City - House 4
  [3344] = {"Cities", "Eastern Cities", "Lilycove", "Dept Store", "1F"}, -- Lilycove City - Department Store 1F
  [3345] = {"Cities", "Eastern Cities", "Lilycove", "Dept Store", "2F"}, -- Lilycove City - Department Store 2F
  [3346] = {"Cities", "Eastern Cities", "Lilycove", "Dept Store", "3F"}, -- Lilycove City - Department Store 3F
  [3347] = {"Cities", "Eastern Cities", "Lilycove", "Dept Store", "4F"}, -- Lilycove City - Department Store 4F
  [3348] = {"Cities", "Eastern Cities", "Lilycove", "Dept Store", "5F"}, -- Lilycove City - Department Store 5F
  [3349] = {"Cities", "Eastern Cities", "Lilycove", "Dept Store", "Rooftop"}, -- Lilycove City - Department Store Rooftop
  [3350] = {"Cities", "Eastern Cities", "Lilycove", "Dept Store", "Elevator"}, -- Lilycove City - Department Store Elevator
  [6441] = {"Other", "S.S. Tidal", "Corridors"}, --  S.S. Tidal - Corridor
  [6442] = {"Other", "S.S. Tidal", "Lower Deck"}, --  S.S. Tidal - Lower Deck
  [6443] = {"Other", "S.S. Tidal", "Rooms"}, --  S.S. Tidal - Rooms
  [6] = {"Cities", "Eastern Cities", "Mossdeep", "Mossdeep City"}, -- Mossdeep City
  [3584] = {"Cities", "Eastern Cities", "Mossdeep", "Gym"}, -- Mossdeep City - Gym
  [3585] = {"Cities", "Eastern Cities", "Mossdeep", "Houses", "House 1"}, -- Mossdeep City - House 1
  [3586] = {"Cities", "Eastern Cities", "Mossdeep", "Houses", "House 2"}, -- Mossdeep City - House 2
  [3587] = {"Cities", "Eastern Cities", "Mossdeep", "Pokemon Center", "Pokemon Center 1F"}, -- Mossdeep City - Pokemon Center 1F
  [3588] = {"Cities", "Eastern Cities", "Mossdeep", "Pokemon Center", "Pokemon Center 2F"}, -- Mossdeep City - Pokemon Center 2F
  [3589] = {"Cities", "Eastern Cities", "Mossdeep", "Mart"}, -- Mossdeep City - Mart
  [3590] = {"Cities", "Eastern Cities", "Mossdeep", "Houses", "House 3"}, -- Mossdeep City - House 3
  [3591] = {"Cities", "Eastern Cities", "Mossdeep", "Houses", "Steven's House"}, -- Mossdeep City - Steven's House
  [3592] = {"Cities", "Eastern Cities", "Mossdeep", "Houses", "House 4"}, -- Mossdeep City - House 4
  [3593] = {"Cities", "Eastern Cities", "Mossdeep", "Space Center", "Space Center 1F"}, -- Mossdeep City - Space Center 1F
  [3594] = {"Cities", "Eastern Cities", "Mossdeep", "Space Center", "Space Center 2F"}, -- Mossdeep City - Space Center 2F
  [3595] = {"Cities", "Eastern Cities", "Mossdeep", "Game Corner"}, -- Mossdeep City - Game Corner 1F
  [7] = {"Cities", "Eastern Cities", "Sootopolis", "Sootopolis City"}, -- Sootopolis City
  [3840] = {"Cities", "Eastern Cities", "Sootopolis", "Gym", "Gym 1F"}, -- Sootopolis City - Gym 1F
  [3841] = {"Cities", "Eastern Cities", "Sootopolis", "Gym", "Gym B1F"}, -- Sootopolis City - Gym B1F
  [3842] = {"Cities", "Eastern Cities", "Sootopolis", "Pokemon Center", "Pokemon Center 1F"}, -- Sootopolis City - Pokemon Center 1F
  [3843] = {"Cities", "Eastern Cities", "Sootopolis", "Pokemon Center", "Pokemon Center 2F"}, -- Sootopolis City - Pokemon Center 2F
  [3844] = {"Cities", "Eastern Cities", "Sootopolis", "Mart"}, -- Sootopolis City - Mart
  [3845] = {"Cities", "Eastern Cities", "Sootopolis", "Houses", "House 1"}, -- Sootopolis City - House 1
  [3846] = {"Cities", "Eastern Cities", "Sootopolis", "Houses", "House 2"}, -- Sootopolis City - House 2
  [3847] = {"Cities", "Eastern Cities", "Sootopolis", "Houses", "House 3"}, -- Sootopolis City - House 3
  [3848] = {"Cities", "Eastern Cities", "Sootopolis", "Houses", "House 4"}, -- Sootopolis City - House 4
  [3849] = {"Cities", "Eastern Cities", "Sootopolis", "Houses", "House 5"}, -- Sootopolis City - House 5
  [3850] = {"Cities", "Eastern Cities", "Sootopolis", "Houses", "House 6"}, -- Sootopolis City - House 6
  [3851] = {"Cities", "Eastern Cities", "Sootopolis", "Houses", "House 7"}, -- Sootopolis City - House 7
  [3852] = {"Cities", "Eastern Cities", "Sootopolis", "Lotad and Seedot House"}, -- Sootopolis City - Lotad & Seedot House
  [3853] = {"Cities", "Eastern Cities", "Sootopolis", "Mystery Event's House", "Mystery Event's House"}, -- Sootopolis City - Mystery Event's House 1F
  -- [3854] = {"Cities", "Eastern Cities", "Sootopolis", "Mystery Event's House", "Mystery Event's House B1F"}, -- Sootopolis City - Mystery Event's House B1F
  [15] = {"Cities", "Eastern Cities", "Pacifidlog", "Pacifidlog Town"}, -- Pacifidlog Town
  [1792] = {"Cities", "Eastern Cities", "Pacifidlog", "Pokemon Center", "Pokemon Center 1F"}, -- Pacifidlog Town - Pokemon Center 1F
  [1793] = {"Cities", "Eastern Cities", "Pacifidlog", "Pokemon Center", "Pokemon Center 2F"}, -- Pacifidlog Town - Pokemon Center 2F
  [1794] = {"Cities", "Eastern Cities", "Pacifidlog", "Houses", "House 1"}, -- Pacifidlog Town - House 1
  [1795] = {"Cities", "Eastern Cities", "Pacifidlog", "Houses", "House 2"}, -- Pacifidlog Town - House 2
  [1796] = {"Cities", "Eastern Cities", "Pacifidlog", "Houses", "House 3"}, -- Pacifidlog Town - House 3
  [1797] = {"Cities", "Eastern Cities", "Pacifidlog", "Houses", "House 4"}, -- Pacifidlog Town - House 4
  [1798] = {"Cities", "Eastern Cities", "Pacifidlog", "Houses", "House 5"}, -- Pacifidlog Town - House 5
  [8] = {"Cities", "Eastern Cities", "Ever Grande", "Ever Grande City"}, -- Ever Grande City
  [4096] = {"Cities", "Eastern Cities", "Ever Grande", "Pokemon League", "Sydney", "Sydney"}, -- Ever Grande City - Sidney's Room
  [4097] = {"Cities", "Eastern Cities", "Ever Grande", "Pokemon League", "Phoebe", "Phoebe"}, -- Ever Grande City - Phoebe's Room
  [4098] = {"Cities", "Eastern Cities", "Ever Grande", "Pokemon League", "Glacia", "Glacia"}, -- Ever Grande City - Glacia's Room
  [4099] = {"Cities", "Eastern Cities", "Ever Grande", "Pokemon League", "Drake", "Drake"}, -- Ever Grande City - Drake's Room
  [4100] = {"Cities", "Eastern Cities", "Ever Grande", "Pokemon League", "Champion", "Champion"}, -- Ever Grande City - Champion's Room
  [4105] = {"Cities", "Eastern Cities", "Ever Grande", "Pokemon League", "Sydney", "Hall"}, -- Ever Grande City - Hall 1
  [4101] = {"Cities", "Eastern Cities", "Ever Grande", "Pokemon League", "Phoebe", "Hall"}, -- Ever Grande City - Hall 2
  [4102] = {"Cities", "Eastern Cities", "Ever Grande", "Pokemon League", "Glacia", "Hall"}, -- Ever Grande City - Hall 3
  [4103] = {"Cities", "Eastern Cities", "Ever Grande", "Pokemon League", "Drake", "Hall"}, -- Ever Grande City - Hall 4
  [4104] = {"Cities", "Eastern Cities", "Ever Grande", "Pokemon League", "Champion", "Hall"}, -- Ever Grande City - Hall 5
  [4106] = {"Cities", "Eastern Cities", "Ever Grande", "Pokemon League", "Pokemon League", "Pokemon League 1F"}, -- Ever Grande City - Pokemon League 1F
  [4107] = {"Cities", "Eastern Cities", "Ever Grande", "Pokemon League", "Hall of Fame"}, -- Ever Grande City - Hall of Fame
  [4108] = {"Cities", "Eastern Cities", "Ever Grande", "Pokemon Center", "Pokemon Center 1F"}, -- Ever Grande City - Pokemon Center 1F
  [4109] = {"Cities", "Eastern Cities", "Ever Grande", "Pokemon Center", "Pokemon Center 2F"}, -- Ever Grande City - Pokemon Center 2F
  [4110] = {"Cities", "Eastern Cities", "Ever Grande", "Pokemon League", "Pokemon League", "Pokemon League 2F"}, -- Ever Grande City - Pokemon League 2F//
  [6155] = {"Routes", "Routes 101-110", "Rt 104", "Petalburg Woods"}, -- Petalburg Woods
  [6148] = {"Routes", "Routes 111-120", "Rt 116", "Rusturf Tunnel"}, -- Rusturf Tunnel
  [6151] = {"Routes", "Routes 101-110", "Rt 106", "Granite Cave", "Granite Cave 1F"}, -- Granite Cave 1F
  [6152] = {"Routes", "Routes 101-110", "Rt 106", "Granite Cave", "Granite Cave B1F"}, -- Granite Cave B1F
  [6153] = {"Routes", "Routes 101-110", "Rt 106", "Granite Cave", "Granite Cave B2F"}, -- Granite Cave B2F
  [6154] = {"Routes", "Routes 101-110", "Rt 106", "Granite Cave", "Granite Cave Steven's Room"}, -- Granite Cave - Steven's Room
  [6158] = {"Routes", "Routes 111-120", "Rt 112", "Fiery Path"}, -- Fiery Path
  [6144] = {"Routes", "Routes 111-120", "Rt 114", "Meteor Falls", "1F1R"}, -- Meteor Falls 1F-1R
  [6145] = {"Routes", "Routes 111-120", "Rt 114", "Meteor Falls", "1F2R"}, -- Meteor Falls 1F-2R
  [6146] = {"Routes", "Routes 111-120", "Rt 114", "Meteor Falls", "B1F1R"}, -- Meteor Falls B1F-1R
  [6147] = {"Routes", "Routes 111-120", "Rt 114", "Meteor Falls", "B1F2R"}, -- Meteor Falls B1F-2R
  [6251] = {"Routes", "Routes 111-120", "Rt 114", "Meteor Falls", "Steven's Room"}, -- Meteor Falls - Steven's Cave
  [6196] = {"Routes", "Routes 101-110", "Rt 110", "New Mauville", "New Mauville Entrance"}, -- New Mauville - Entrance
  [6197] = {"Routes", "Routes 101-110", "Rt 110", "New Mauville", "New Mauville"}, -- New Mauville - Inside
  [6198] = {"Routes", "Routes 101-110", "Rt 108", "Abandoned Ship", "Abandoned Ship 1F", "Abandoned Ship Deck"}, -- Abandoned Ship - Deck
  [6199] = {"Routes", "Routes 101-110", "Rt 108", "Abandoned Ship", "Abandoned Ship 1F", "Abandoned Ship Corridors 1F"}, -- Abandoned Ship - Corridors 1F
  [6200] = {"Routes", "Routes 101-110", "Rt 108", "Abandoned Ship", "Abandoned Ship 1F", "Abandoned Ship Rooms 1 1F"}, -- Abandoned Ship - Rooms 1F
  [6201] = {"Routes", "Routes 101-110", "Rt 108", "Abandoned Ship", "Abandoned Ship B1F", "Abandoned Ship Corridors B1F"}, -- Abandoned Ship - Corridors B1F
  [6202] = {"Routes", "Routes 101-110", "Rt 108", "Abandoned Ship", "Abandoned Ship B1F", "Abandoned Ship Rooms 1 B1F"}, -- Abandoned Ship - Rooms B1F
  [6203] = {"Routes", "Routes 101-110", "Rt 108", "Abandoned Ship", "Abandoned Ship B1F", "Abandoned Ship Rooms 2 B1F"}, -- Abandoned Ship - Rooms 2 B1F
  [6204] = {"Routes", "Routes 101-110", "Rt 108", "Abandoned Ship", "Abandoned Ship Hidden Floor", "Abandoned Ship Underwater 1"}, -- Abandoned Ship - Underwater 1
  [6205] = {"Routes", "Routes 101-110", "Rt 108", "Abandoned Ship", "Abandoned Ship B1F", "Abandoned Ship Storage Room B1F"}, -- Abandoned Ship - Room B1F
  [6206] = {"Routes", "Routes 101-110", "Rt 108", "Abandoned Ship", "Abandoned Ship 1F", "Abandoned Ship Rooms 2 1F"}, -- Abandoned Ship - Rooms 2 1F
  [6207] = {"Routes", "Routes 101-110", "Rt 108", "Abandoned Ship", "Abandoned Ship 1F", "Abandoned Ship Captain's Office"}, -- Abandoned Ship - Captain's Office
  [6208] = {"Routes", "Routes 101-110", "Rt 108", "Abandoned Ship", "Abandoned Ship Hidden Floor", "Abandoned Ship Underwater 2"}, -- Abandoned Ship - Underwater 2
  [6209] = {"Routes", "Routes 101-110", "Rt 108", "Abandoned Ship", "Abandoned Ship Hidden Floor", "Abandoned Ship Hidden Floor Corridors"}, -- Abandoned Ship - Hidden Floor Corridors
  [6210] = {"Routes", "Routes 101-110", "Rt 108", "Abandoned Ship", "Abandoned Ship Hidden Floor", "Abandoned Ship Hidden Floor Rooms"}, -- Abandoned Ship - Hidden Floor Rooms
  [6159] = {"Routes", "Routes 121-130", "Rt 122", "Mt. Pyre", "Interior", "1F"}, -- Mt. Pyre 1F
  [6160] = {"Routes", "Routes 121-130", "Rt 122", "Mt. Pyre", "Interior", "2F"}, -- Mt. Pyre 2F
  [6161] = {"Routes", "Routes 121-130", "Rt 122", "Mt. Pyre", "Interior", "3F"}, -- Mt. Pyre 3F
  [6162] = {"Routes", "Routes 121-130", "Rt 122", "Mt. Pyre", "Interior", "4F"}, -- Mt. Pyre 4F
  [6163] = {"Routes", "Routes 121-130", "Rt 122", "Mt. Pyre", "Interior", "5F"}, -- Mt. Pyre 5F
  [6164] = {"Routes", "Routes 121-130", "Rt 122", "Mt. Pyre", "Interior", "6F"}, -- Mt. Pyre 6F
  [6165] = {"Routes", "Routes 121-130", "Rt 122", "Mt. Pyre", "Exterior", "Exterior"}, -- Mt. Pyre Exterior
  [6166] = {"Routes", "Routes 121-130", "Rt 122", "Mt. Pyre", "Exterior", "Summit"}, -- Mt. Pyre Summit
  [6230] = {"Routes", "Routes 111-120", "Rt 112", "Magma Hideout", "1F"}, -- Magma Hideout 1F
  [6231] = {"Routes", "Routes 111-120", "Rt 112", "Magma Hideout", "2F1R"}, -- Magma Hideout 2F-1R
  [6232] = {"Routes", "Routes 111-120", "Rt 112", "Magma Hideout", "2F2R"}, -- Magma Hideout 2F-2R
  [6233] = {"Routes", "Routes 111-120", "Rt 112", "Magma Hideout", "3F1R"}, -- Magma Hideout 3F-1R
  [6234] = {"Routes", "Routes 111-120", "Rt 112", "Magma Hideout", "3F2R"}, -- Magma Hideout 3F-2R
  [6235] = {"Routes", "Routes 111-120", "Rt 112", "Magma Hideout", "4F"}, -- Magma Hideout 4F
  [6236] = {"Routes", "Routes 111-120", "Rt 112", "Magma Hideout", "3F3R"}, -- Magma Hideout 3F-3R
  [6237] = {"Routes", "Routes 111-120", "Rt 112", "Magma Hideout", "2F3R"}, -- Magma Hideout 2F-3R
  [6167] = {"Cities", "Eastern Cities", "Lilycove", "Aqua Hideout", "Aqua Hideout 1F"}, -- Aqua Hideout 1F
  [6168] = {"Cities", "Eastern Cities", "Lilycove", "Aqua Hideout", "Aqua Hideout B1F"}, -- Aqua Hideout B1F
  [6169] = {"Cities", "Eastern Cities", "Lilycove", "Aqua Hideout", "Aqua Hideout B2F"}, -- Aqua Hideout B2F
  [6190] = {"Routes", "Routes 121-130", "Rt 125", "Shoal Cave", "Low Tide", "Entrance Room"}, -- Shoal Cave Low Tide - Entrance Room
  [6191] = {"Routes", "Routes 121-130", "Rt 125", "Shoal Cave", "Low Tide", "Inner Room"}, -- Shoal Cave Low Tide - Inner Room
  [6192] = {"Routes", "Routes 121-130", "Rt 125", "Shoal Cave", "Low Tide", "Stairs Room"}, -- Shoal Cave Low Tide - Stairs Room
  [6193] = {"Routes", "Routes 121-130", "Rt 125", "Shoal Cave", "Low Tide", "Lower Room"}, -- Shoal Cave Low Tide - Lower Room
  [6194] = {"Routes", "Routes 121-130", "Rt 125", "Shoal Cave", "High Tide", "Entrance Room"}, -- Shoal Cave High Tide - Entrance Room
  [6195] = {"Routes", "Routes 121-130", "Rt 125", "Shoal Cave", "High Tide", "Inner Room"}, -- Shoal Cave High Tide - Inner Room
  [6227] = {"Routes", "Routes 121-130", "Rt 125", "Shoal Cave", "Low Tide", "Ice Room"}, -- Shoal Cave Low Tide - Ice Room
  [6170] = {"Routes", "Routes 121-130", "Rt 128", "Seafloor Cavern", "Underwater"}, -- Seafloor Cavern - Underwater
  [6171] = {"Routes", "Routes 121-130", "Rt 128", "Seafloor Cavern", "Entrance"}, -- Seafloor Cavern - Entrance
  [6172] = {"Routes", "Routes 121-130", "Rt 128", "Seafloor Cavern", "1"}, -- Seafloor Cavern - Room 1
  [6173] = {"Routes", "Routes 121-130", "Rt 128", "Seafloor Cavern", "2"}, -- Seafloor Cavern - Room 2
  [6174] = {"Routes", "Routes 121-130", "Rt 128", "Seafloor Cavern", "3"}, -- Seafloor Cavern - Room 3
  [6175] = {"Routes", "Routes 121-130", "Rt 128", "Seafloor Cavern", "4"}, -- Seafloor Cavern - Room 4
  [6176] = {"Routes", "Routes 121-130", "Rt 128", "Seafloor Cavern", "5"}, -- Seafloor Cavern - Room 5
  [6177] = {"Routes", "Routes 121-130", "Rt 128", "Seafloor Cavern", "6"}, -- Seafloor Cavern - Room 6
  [6178] = {"Routes", "Routes 121-130", "Rt 128", "Seafloor Cavern", "7"}, -- Seafloor Cavern - Room 7
  [6179] = {"Routes", "Routes 121-130", "Rt 128", "Seafloor Cavern", "8"}, -- Seafloor Cavern - Room 8
  [6180] = {"Routes", "Routes 121-130", "Rt 128", "Seafloor Cavern", "9"}, -- Seafloor Cavern - Room 9
  [6187] = {"Cities", "Eastern Cities", "Evergrande", "Victory Road", "Victory Road 1F"}, -- Victory Road 1F
  [6188] = {"Cities", "Eastern Cities", "Evergrande", "Victory Road", "Victory Road B1F"}, -- Victory Road B1F
  [6189] = {"Cities", "Eastern Cities", "Evergrande", "Victory Road", "Victory Road B2F"}, -- Victory Road B2F
  [6243] = {"Other", "Battle Frontier", "Artisan Cave", "B1F"}, -- Artisan Cave B1F
  [6244] = {"Other", "Battle Frontier", "Artisan Cave", "1F"}, -- Artisan Cave 1F
  [6212] = {"Routes", "Routes 111-120", "Rt 120", "Ancient Tomb"}, -- Ancient Tomb
  [6181] = {"Cities", "Eastern Cities", "Sootopolis", "Cave of Origin", "Cave of Origin Entrance"}, -- Cave of Origin - Entrance
  [6182] = {"Cities", "Eastern Cities", "Sootopolis", "Cave of Origin", "Cave of Origin 1F"}, -- Cave of Origin 1F
  [6186] = {"Cities", "Eastern Cities", "Sootopolis", "Cave of Origin", "Cave of Origin B1F"}, -- Cave of Origin B1F
  [6150] = {"Routes", "Routes 111-120", "Rt 111", "Desert Ruins"}, -- Desert Ruins
  [6242] = {"Routes", "Routes 111-120", "Rt 114", "Fossil Maniac", "Desert Underpass"}, -- Desert Underpass
  [6211] = {"Routes", "Routes 101-110", "Rt 105", "Island Cave"}, -- Island Cave
  [6246] = {"Other", "Marine Cave", "Entrance"}, -- Marine Cave - Entrance
  [6247] = {"Other", "Marine Cave", "End"}, -- Marine Cave - End
  [6238] = {"Routes", "Routes 111-120", "Rt 111", "Mirage Tower", "1F"}, -- Mirage Tower 1F
  [6239] = {"Routes", "Routes 111-120", "Rt 111", "Mirage Tower", "2F"}, -- Mirage Tower 2F
  [6240] = {"Routes", "Routes 111-120", "Rt 111", "Mirage Tower", "3F"}, -- Mirage Tower 3F
  [6241] = {"Routes", "Routes 111-120", "Rt 111", "Mirage Tower", "4F"}, -- Mirage Tower 4F
  [6213] = {"Routes", "Routes 131-134", "Rt 134", "Sealed Chamber", "Underwater Entry"}, -- Sealed Chamber - Outer Room
  [6214] = {"Routes", "Routes 131-134", "Rt 134", "Sealed Chamber", "Underwater Path"}, -- Sealed Chamber - Outer Room
  [6215] = {"Routes", "Routes 131-134", "Rt 134", "Sealed Chamber", "Outer Room"}, -- Sealed Chamber - Outer Room
  [6216] = {"Routes", "Routes 131-134", "Rt 134", "Sealed Chamber", "Inner Room"}, -- Sealed Chamber - Inner Room
  [6221] = {"Routes", "Routes 131-134", "Rt 131", "Sky Pillar", "Entrance"}, -- Sky Pillar - Entrance
  [6222] = {"Routes", "Routes 131-134", "Rt 131", "Sky Pillar", "Outside"}, -- Sky Pillar - Outside
  [6223] = {"Routes", "Routes 131-134", "Rt 131", "Sky Pillar", "1F"}, -- Sky Pillar 1F
  [6224] = {"Routes", "Routes 131-134", "Rt 131", "Sky Pillar", "2F"}, -- Sky Pillar 2F
  [6225] = {"Routes", "Routes 131-134", "Rt 131", "Sky Pillar", "3F"}, -- Sky Pillar 3F
  [6226] = {"Routes", "Routes 131-134", "Rt 131", "Sky Pillar", "4F"}, -- Sky Pillar 4F
  [6228] = {"Routes", "Routes 131-134", "Rt 131", "Sky Pillar", "5F"}, -- Sky Pillar 5F
  [6229] = {"Routes", "Routes 131-134", "Rt 131", "Sky Pillar", "Top"}, -- Sky Pillar - Top
  [6248] = {"Other", "Terra Cave", "Entrance"}, -- Terra Cave - Entrance
  [6249] = {"Other", "Terra Cave", "End"}, -- Terra Cave - End
  [6665] = {"Other", "Southern Island", "Exterior"}, -- Southern Island - Exterior
  [6660] = {"Other", "Battle Frontier", "Battle Frontier"}, -- Battle Frontier
  [6666] = {"Other", "Southern Island", "Interior"}, -- Southern Island - Interior
  [6712] = {"Other", "Faraway Island", "Exterior"}, -- Faraway Island - Entrance
  [6713] = {"Other", "Faraway Island", "Interior"}, -- Faraway Island - Interior
  [6714] = {"Other", "Birth Island", "Exterior"}, -- Birth Island - Exterior
  [6715] = {"Other", "Birth Island", "Harbor"}, -- Birth Island - Harbor
  [6722] = {"Other", "Navel Rock", "Exterior"}, -- Navel Rock - Exterior
  [6723] = {"Other", "Navel Rock", "Harbor"}, -- Navel Rock - Harbor
  [6724] = {"Other", "Navel Rock", "Entrance"}, -- Navel Rock - Entrance
  [6725] = {"Other", "Navel Rock", "B1F"}, -- Navel Rock B1F
  [6726] = {"Other", "Navel Rock", "Fork"}, -- Navel Rock - Fork
  [6727] = {"Other", "Navel Rock", "Up", "1"}, -- Navel Rock - Up 1
  [6728] = {"Other", "Navel Rock", "Up", "2"}, -- Navel Rock - Up 2
  [6729] = {"Other", "Navel Rock", "Up", "3"}, -- Navel Rock - Up 3
  [6730] = {"Other", "Navel Rock", "Up", "4"}, -- Navel Rock - Up 4
  [6731] = {"Other", "Navel Rock", "Up", "Top"}, -- Navel Rock - Top
  [6732] = {"Other", "Navel Rock", "Down", "1"}, -- Navel Rock - Down 1
  [6733] = {"Other", "Navel Rock", "Down", "2"}, -- Navel Rock - Down 2
  [6734] = {"Other", "Navel Rock", "Down", "3"}, -- Navel Rock - Down 3
  [6735] = {"Other", "Navel Rock", "Down", "4"}, -- Navel Rock - Down 4
  [6736] = {"Other", "Navel Rock", "Down", "5"}, -- Navel Rock - Down 5
  [6737] = {"Other", "Navel Rock", "Down", "6"}, -- Navel Rock - Down 6
  [6738] = {"Other", "Navel Rock", "Down", "7"}, -- Navel Rock - Down 7
  [6739] = {"Other", "Navel Rock", "Down", "8"}, -- Navel Rock - Down 8
  [6740] = {"Other", "Navel Rock", "Down", "9"}, -- Navel Rock - Down 9
  [6741] = {"Other", "Navel Rock", "Down", "10"}, -- Navel Rock - Down 10
  [6742] = {"Other", "Navel Rock", "Down", "11"}, -- Navel Rock - Down 11
  [6743] = {"Other", "Navel Rock", "Down", "Bottom"}, -- Navel Rock - Bottom
  [16] = {"Routes", "Routes 101-110", "Rt 101", "Rt 101"}, -- Route 101
  [17] = {"Routes", "Routes 101-110", "Rt 102", "Rt 102"}, -- Route 102
  [18] = {"Routes", "Routes 101-110", "Rt 103", "Rt 103"}, -- Route 103
  [19] = {"Routes", "Routes 101-110", "Rt 104", "Rt 104"}, -- Route 104
  [4352] = {"Routes", "Routes 101-110", "Rt 104", "Mr. Briney's House"}, -- Route 104 - Mr. Briney's House
  [4353] = {"Routes", "Routes 101-110", "Rt 104", "Pretty Petal Flower Shop"}, -- Route 104 - Pretty Petal Flower Shop
  [20] = {"Routes", "Routes 101-110", "Rt 105", "Rt 105"}, -- Route 105
  [21] = {"Routes", "Routes 101-110", "Rt 106", "Rt 106"}, -- Route 106
  [22] = {"Routes", "Routes 101-110", "Rt 107", "Rt 107"}, -- Route 107
  [23] = {"Routes", "Routes 101-110", "Rt 108", "Rt 108"}, -- Route 108
  [24] = {"Routes", "Routes 101-110", "Rt 109", "Rt 109"}, -- Route 109
  [7168] = {"Routes", "Routes 101-110", "Rt 109", "Seashore House"}, -- Route 109 - Seashore House
  [25] = {"Routes", "Routes 101-110", "Rt 110", "Rt 110"}, -- Route 110
  [7435] = {"Routes", "Routes 101-110", "Rt 110", "Cycling Road", "Cycling Road Entrance North"}, -- Route 110 - Seaside Cycling Road North Entrance
  [7436] = {"Routes", "Routes 101-110", "Rt 110", "Cycling Road", "Cycling Road Entrance South"}, -- Route 110 - Seaside Cycling Road South Entrance
  [7424] = {"Routes", "Routes 101-110", "Rt 110", "Trick House", "Trick House Entrance"}, -- Trick House - Entrance
  [7425] = {"Routes", "Routes 101-110", "Rt 110", "Trick House", "Trick House End"}, -- Trick House - End
  [7426] = {"Routes", "Routes 101-110", "Rt 110", "Trick House", "Trick House Corridor"}, -- Trick House - Corridor
  [7427] = {"Routes", "Routes 101-110", "Rt 110", "Trick House", "Trick House Puzzle 1"}, -- Trick House - Puzzle 1
  [7428] = {"Routes", "Routes 101-110", "Rt 110", "Trick House", "Trick House Puzzle 2"}, -- Trick House - Puzzle 2
  [7429] = {"Routes", "Routes 101-110", "Rt 110", "Trick House", "Trick House Puzzle 3"}, -- Trick House - Puzzle 3
  [7430] = {"Routes", "Routes 101-110", "Rt 110", "Trick House", "Trick House Puzzle 4"}, -- Trick House - Puzzle 4
  [7431] = {"Routes", "Routes 101-110", "Rt 110", "Trick House", "Trick House Puzzle 5"}, -- Trick House - Puzzle 5
  [7432] = {"Routes", "Routes 101-110", "Rt 110", "Trick House", "Trick House Puzzle 6"}, -- Trick House - Puzzle 6
  [7433] = {"Routes", "Routes 101-110", "Rt 110", "Trick House", "Trick House Puzzle 7"}, -- Trick House - Puzzle 7
  [7434] = {"Routes", "Routes 101-110", "Rt 110", "Trick House", "Trick House Puzzle 8"}, -- Trick House - Puzzle 8
  [26] = {"Routes", "Routes 111-120", "Rt 111", "Rt 111"}, -- Route 111
  [4608] = {"Routes", "Routes 111-120", "Rt 111", "Winstrate Family's House"}, -- Route 111 - Winstrate Family's House
  [4609] = {"Routes", "Routes 111-120", "Rt 111", "Old Lady's Rest Stop"}, -- Route 111 - Old Lady's Rest Stop
  [27] = {"Routes", "Routes 111-120", "Rt 112", "Rt 112"}, -- Route 112
  [4864] = {"Routes", "Routes 111-120", "Rt 112", "Cable Car Station"}, -- Route 112 - Cable Car Station
  [28] = {"Routes", "Routes 111-120", "Rt 113", "Rt 113"}, -- Route 113
  [7680] = {"Routes", "Routes 111-120", "Rt 113", "Glass Workshop"}, -- Route 113 - Glass Workshop
  [29] = {"Routes", "Routes 111-120", "Rt 114", "Rt 114"}, -- Route 114
  [5120] = {"Routes", "Routes 111-120", "Rt 114", "Fossil Maniac", "House"}, -- Route 114 - Fossil Maniac's House
  [5121] = {"Routes", "Routes 111-120", "Rt 114", "Fossil Maniac", "Tunnel"}, -- Route 114 - Fossil Maniac's Tunnel
  [5122] = {"Routes", "Routes 111-120", "Rt 114", "Lanette's House"}, -- Route 114 - Lanette's House
  [30] = {"Routes", "Routes 111-120", "Rt 115", "Rt 115"}, -- Route 115
  [31] = {"Routes", "Routes 111-120", "Rt 116", "Rt 116"}, -- Route 116
  [5376] = {"Routes", "Routes 111-120", "Rt 116", "Tunneler's Rest House"}, -- Route 116 - Tunneler's Rest House
  [32] = {"Routes", "Routes 111-120", "Rt 117", "Rt 117"}, -- Route 117
  [5632] = {"Routes", "Routes 111-120", "Rt 117", "Pokemon Daycare"}, -- Route 117 - Pokemon Daycare
  [33] = {"Routes", "Routes 111-120", "Rt 118", "Rt 118"}, -- Route 118
  [34] = {"Routes", "Routes 111-120", "Rt 119", "Rt 119"}, -- Route 119
  [8194] = {"Routes", "Routes 111-120", "Rt 119", "House"}, -- Route 119 - House
  [8192] = {"Routes", "Routes 111-120", "Weather Institute", "Weather Institute 1F"}, -- Weather Institute 1F
  [8193] = {"Routes", "Routes 111-120", "Weather Institute", "Weather Institute 2F"}, -- Weather Institute 2F
  [35] = {"Routes", "Routes 111-120", "Rt 120", "Rt 120"}, -- Route 120
  [6217] = {"Routes", "Routes 111-120", "Rt 120", "Scorched Slab"}, -- Route 120 - Scorched Slab
  [36] = {"Routes", "Routes 121-130", "Rt 121", "Rt 121"}, -- Route 121
  [37] = {"Routes", "Routes 121-130", "Rt 122", "Rt 122"}, -- Route 122
  [38] = {"Routes", "Routes 121-130", "Rt 123", "Rt 123"}, -- Route 123
  [7936] = {"Routes", "Routes 121-130", "Rt 123", "Berry Master's House"}, -- Route 123 - Berry Master's House
  [39] = {"Routes", "Routes 121-130", "Rt 124", "Rt 124", "Rt 124"}, -- Route 124
  [55] = {"Routes", "Routes 101-110", "Rt 105", "Rt 105", "Underwater"}, -- Route 105 Underwater
  [50] = {"Routes", "Routes 121-130", "Rt 124", "Rt 124", "Underwater"}, -- Route 124 Underwater
  [51] = {"Routes", "Routes 121-130", "Rt 126", "Rt 126", "Underwater"}, -- Route 126 Underwater
  [6149] = {"Routes", "Routes 121-130", "Rt 126", "Rt 126", "Underwater Entry"}, -- Route 126 Underwater Entry to Sootopolis
  [52] = {"Routes", "Routes 121-130", "Rt 127", "Rt 127", "Underwater"}, -- Route 127 Underwater
  [53] = {"Routes", "Routes 121-130", "Rt 128", "Rt 128", "Underwater"}, -- Route 128 Underwater
  [54] = {"Routes", "Routes 121-130", "Rt 129", "Rt 129", "Underwater"}, -- Route 129 Underwater
  [8448] = {"Routes", "Routes 121-130", "Rt 124", "Diving Treasure Hunter's House"}, -- Route 124 - Diving Treasure Hunter's House
  [40] = {"Routes", "Routes 121-130", "Rt 125", "Rt 125"}, -- Route 125
  [41] = {"Routes", "Routes 121-130", "Rt 126", "Rt 126"}, -- Route 126
  [42] = {"Routes", "Routes 121-130", "Rt 127", "Rt 127"}, -- Route 127
  [43] = {"Routes", "Routes 121-130", "Rt 128", "Rt 128"}, -- Route 128
  [44] = {"Routes", "Routes 121-130", "Rt 129", "Rt 129"}, -- Route 129
  [45] = {"Routes", "Routes 121-130", "Rt 130", "Rt 130"}, -- Route 130
  [46] = {"Routes", "Routes 131-134", "Rt 131", "Rt 131"}, -- Route 131
  [47] = {"Routes", "Routes 131-134", "Rt 132", "Rt 132"}, -- Route 132
  [48] = {"Routes", "Routes 131-134", "Rt 133", "Rt 133"}, -- Route 133
  [49] = {"Routes", "Routes 131-134", "Rt 134", "Rt 134"}, -- Route 134
  [6156] = {"Routes", "Routes 111-120", "Rt 112", "Mt. Chimney", "Mt. Chimney"}, -- Mt. Chimney
  [4865] = {"Routes", "Routes 111-120",  "Rt 112", "Cable Car Station"}, -- Mt. Chimney - Cable Car Station
  [6157] = {"Routes", "Routes 111-120", "Rt 112", "Jagged Pass"}, -- Jagged Pass
  [5888] = {"Routes", "Routes 121-130", "Rt 121", "Safari Zone", "Lobby"}, -- Safari Zone - Entrance
  [6656] = {"Routes", "Routes 121-130", "Rt 121", "Safari Zone", "Northwest"}, -- Safari Zone - Northwest
  [6657] = {"Routes", "Routes 121-130", "Rt 121", "Safari Zone", "North"}, -- Safari Zone - North
  [6658] = {"Routes", "Routes 121-130", "Rt 121", "Safari Zone", "Southwest"}, -- Safari Zone - Southwest
  [6659] = {"Routes", "Routes 121-130", "Rt 121", "Safari Zone", "South"}, -- Safari Zone - South
  [6667] = {"Routes", "Routes 121-130", "Rt 121", "Safari Zone", "Rest House"}, -- Safari Zone - Rest House
  [6668] = {"Routes", "Routes 121-130", "Rt 121", "Safari Zone", "Northeast"}, -- Safari Zone - Northeast
  [6669] = {"Routes", "Routes 121-130", "Rt 121", "Safari Zone", "Southeast"}, -- Safari Zone - Southeast
}
